name: Build, deploy and release

on:
  push: 
    branches: 
      - prod
      # - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'infra-test'
        type: choice
        options:
          - infra-test
          - infra

permissions:
  contents: write
  packages: write

jobs:
  build-publish:
    uses: ./.github/workflows/.build-publish-docker.yaml
    secrets: inherit

  deploy-infra-test:
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'infra-test')
    uses: ./.github/workflows/.cluster-deploy.yaml
    needs: build-publish
    secrets: inherit
    with:
      environment: infra-test
      image-tags: ${{ needs.build-publish.outputs.image-tags }}

  deploy-infra:
    if: github.ref == 'refs/heads/prod' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'infra')
    uses: ./.github/workflows/.cluster-deploy.yaml
    needs: build-publish
    secrets: inherit
    with:
      environment: infra
      image-tags: ${{ needs.build-publish.outputs.image-tags }}

  create-release: 
    if: github.ref == 'refs/heads/prod'
    uses: ./.github/workflows/.create-release.yaml
    needs: deploy-infra
    secrets: inherit